openapi: 3.0.1
info:
  contact:
    email: lampralexandros@gmail.com
  description: This is a sample openApi document
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://wabli.netlify.app/
  title: TempApi
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- description: solid-spoon
  url: http://83.212.100.226:3001/v1
security:
- {}
tags:
- description: not yet ready
  name: blog
paths:
  /blog:
    post:
      operationId: createblog
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/blog'
        description: data to be created
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/blog'
          description: successful operation
      summary: Creates the data
      tags:
      - blog
      x-eov-operation-handler: controllers/BlogController
  /blog/{blogId}:
    delete:
      operationId: deleteblog
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: blogId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: successful operation
      summary: Delete the element
      tags:
      - blog
      x-eov-operation-handler: controllers/BlogController
    get:
      operationId: getblog
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: blogId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/blog'
          description: successful operation
      summary: Get the element
      tags:
      - blog
      x-eov-operation-handler: controllers/BlogController
    put:
      operationId: updateblog
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: blogId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/blog'
        description: data to be updated
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/blog'
          description: successful operation
      summary: Updates the element
      tags:
      - blog
      x-eov-operation-handler: controllers/BlogController
  /blog/getAll:
    get:
      operationId: getAllblog
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/blog'
                type: array
          description: successful operation
      summary: Get all the data
      tags:
      - blog
      x-method-getAll: "true"
      x-eov-operation-handler: controllers/BlogController
components:
  schemas:
    blog:
      example:
        stext: stext
        _id: _id
      properties:
        _id:
          type: string
        stext:
          type: string
      required:
      - stext
      type: object
